### ISSUE TITLE
Downloaded fastq files are too big for the storage

### ISSUE THREAD

**Issue by guanxiangliang** [louiejtaylor/hisss#10]

**Comment by louiejtaylor** [comment]
Mitigation: gzip output

- [x] Zip output of fastq-dump
- [ ] Add pigz to requirements.txt

**Comment by ressy** [comment]
Aha you beat me to opening this issue by one hour Guanxiang ;)

fastq-dump has --gzip and --bzip2 out of the box, so maybe just use one of those?  Then you won't need to add more dependencies, I think.

**Comment by louiejtaylor** [comment]
Ooh, thanks @ressy! Always a step ahead
